### ISSUE TITLE
Build out initial main apps: notifications and sensors

### ISSUE THREAD

**Issue by bkeating** [Corvia/thermonitor#2]
This (mostly) means data models but admin.py should also be built out a bit (and the admin app enabled!)

**Comment by dsilvers** [comment]
v.00001 of email template.

<img width="933" alt="test_sensor_temperature_alert_-_55__f_-_dan_silvers_net_-_silvers_networks_mail" src="https://cloud.githubusercontent.com/assets/284929/11073353/ea4268c4-87af-11e5-8071-660d16029f5a.png">

**Comment by dsilvers** [comment]
Mostly complete, needs testing and a pull request. API is now connected to the models via signals.
